//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM580Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int MedicationId { get; set; }
        public int AppointmentAppointmentId { get; set; }
        public string Name { get; set; }
        public string Dosage { get; set; }
        public string Strength { get; set; }
        public int ChildChildId { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Child Child { get; set; }
    }
}
